//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogue_Produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogue_Produits()
        {
            this.acheter = new HashSet<acheter>();
            this.Entreprise = new HashSet<Entreprise>();
        }
    
        public int num_produit { get; set; }
        public string nom_produit { get; set; }
        public Nullable<int> ref_fournisseur { get; set; }
        public string libelle_court { get; set; }
        public string libelle_long { get; set; }
        public string ss_rubrique { get; set; }
        public string rubrique { get; set; }
        public Nullable<double> prix_achat { get; set; }
        public Nullable<double> prix_vente { get; set; }
        public Nullable<double> taux_tva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acheter> acheter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entreprise> Entreprise { get; set; }
    }
}
