//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.Entreprise = new HashSet<Entreprise>();
            this.Clients = new HashSet<Clients>();
        }
    
        public int num_facture { get; set; }
        public Nullable<int> num_ref_client { get; set; }
        public Nullable<int> num_bon_livraison { get; set; }
        public Nullable<int> num_reglement { get; set; }
        public Nullable<System.DateTime> date_commande { get; set; }
        public Nullable<System.DateTime> date_facturation { get; set; }
        public Nullable<double> montant { get; set; }
        public string ref_produit { get; set; }
        public Nullable<int> qte_produit { get; set; }
        public Nullable<int> qte_commander { get; set; }
        public string paiement_differer { get; set; }
        public Nullable<double> reduction { get; set; }
        public string address_facturation { get; set; }
        public string address_livraison { get; set; }
        public string commande_en_cours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entreprise> Entreprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
