//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class materiel_villageEntities : DbContext
    {
        public materiel_villageEntities()
            : base("name=materiel_villageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acheter> acheter { get; set; }
        public virtual DbSet<Catalogue_Produits> Catalogue_Produits { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
    }
}
